### ISSUE TITLE
Новый функционал 

### ISSUE THREAD

**Issue by moclauq** [Kene33/receiving-suggestions-bot#1]
### Добавить команды для модеров, /warn /mute /ban 

Пример : 
`/mute (1m/h/d)  (Причина мута)
`
Действие : 
Дает мут человеку на сообщение которого произвелся реплай, делать способами тг а не костылить через таймдельту 
также после выдачи мута хочу кнопку "Размутить" и человека размутит с последуйщим сообщением. 
После выдачи 3 варнов выдается бан.
Если есть возможность у бота писать в личку то пиши что забанило. 
Ну и про разрешения не забудь.

### Каптча
Нужно чтобы при входе человеку выдавался мут, после его тэгает и пишет сообщение 
рандомно выбирался 1 из 3 списков с символами и из него делались кнопочки и также рандомно выбирался 1 символ из списка и писался в сообщении и при нажатии на него размучивался если прошло 60 секунд или нажал неправильную кнопку он кикнет и при следуйщей попытки входа попросит подождать 30 секунд.

### Мелкие задачи

- Добавь файл локализации и настройки в формате yaml.
- Убери возможность отправлять в предложку сообщения админам, а также сделай команду /ban 1m/h/d или навсегда для блокировки в предложке.

**Comment by Kene33** [comment]
Хорошо я попробую

**Comment by Kene33** [comment]
крайне лень и возможно потом сделаю отдельного тг бота для модерации чата
